on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  compare_versions:
    name: Sync Zig versions across codebase
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Compare Zig versions
        shell: bash
        run: |
          sudo apt install -y ripgrep

          build_version="$(rg 'required_zig = "(.*)"' -Nor '$1' ./build.zig)"
          flake_version="$(nix develop --command zig version)"
          tests_version="$(rg 'version: (.*)' -Nor '$1' ./.github/workflows/zig_tests.yml)"

          if [[
            "$build_version" != "$flake_version" ||
            "$build_version" != "$tests_version"
          ]]; then
            printf 'FATAL: Zig versions are mismatched!\n\n'
            printf 'build.zig:     %s\n' "$build_version"
            printf 'flake.nix:     %s\n' "$flake_version"
            printf 'zig_tests.yml: %s\n' "$tests_version"
            exit 1
          else
            echo "Zig versions are synced. Exiting."
            exit 0
          fi
